package it.polito.esc.bean;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class CardLiteView implements Serializable, Cloneable {

	private static final long serialVersionUID = 4121992091220241403L;

	/**
	 * The card number using the algorithm RFC-4122 version 1, use /api/v2/cards/generate-escn to generate a valid card number or leave it blank and it will be autogenerated (POST ONLY)
	 * 
	 * example: 3e506370-826a-103d-bf76-001000000001
	 */
	@JsonProperty("cardNumber")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("cardNumber")
	@Expose
	private String cardNumber;

	/**
	 * The name displayed on the card
	 * 
	 * example: Card of John
	 */
	@JsonProperty("displayName")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("displayName")
	@Expose
	private String displayName;

	/**
	 * The expiration date of the card (yyyy-MM-dd ISO-8601)
	 * 
	 * example: 2022-12-31
	 */
	@JsonProperty("expiresAt")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("expiresAt")
	@Expose
	private Date expiresAt;

	/**
	 * The issued date of the card (yyyy-MM-dd ISO-8601)
	 * 
	 * example: 2022-12-31
	 */
	@JsonProperty("issuedAt")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("issuedAt")
	@Expose
	private Date issuedAt;

	@JsonProperty("issuer")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("issuer")
	@Expose
	private OrganisationLiteView issuer;

	@JsonProperty("person")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@SerializedName("person")
	@Expose
	private PersonLiteView person;

	public CardLiteView() {
		super();
	}

	public CardLiteView(String cardNumber, String displayName, Date expiresAt, Date issuedAt,
			OrganisationLiteView issuer, PersonLiteView person) {
		super();
		this.cardNumber = cardNumber;
		this.displayName = displayName;
		this.expiresAt = expiresAt;
		this.issuedAt = issuedAt;
		this.issuer = issuer;
		this.person = person;
	}

	public String getCardNumber() {
		return cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Date getExpiresAt() {
		return expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public Date getIssuedAt() {
		return issuedAt;
	}

	public void setIssuedAt(Date issuedAt) {
		this.issuedAt = issuedAt;
	}

	public OrganisationLiteView getIssuer() {
		return issuer;
	}

	public void setIssuer(OrganisationLiteView issuer) {
		this.issuer = issuer;
	}

	public PersonLiteView getPerson() {
		return person;
	}

	public void setPerson(PersonLiteView person) {
		this.person = person;
	}

	@Override
	public CardLiteView clone() {
		return new CardLiteView(this.cardNumber, this.displayName, this.expiresAt, this.issuedAt,
				this.issuer != null ? this.issuer.clone() : null, this.person != null ? this.person.clone() : null);
	}

	@Override
	public String toString() {
		return "CardLiteView [cardNumber=" + cardNumber + ", displayName=" + displayName + ", expiresAt=" + expiresAt
				+ ", issuedAt=" + issuedAt + ", issuer=" + issuer + ", person=" + person + "]";
	}

}
